### PR TITLE
fix: useSpring ssr fix

### PR DESCRIPTION
**Pull request by DennisSmuda**
Hey @posva thanks so much for this!
I ran into a little issue while trying to use with nuxt and found a quick fix 👍 

Let me know if you need more info or a way to reproduce :)

### CODE REVIEW

**Comment by posva** [comment]
Thanks but this seems to already work in SSR 🤔 
Reading that code made me realize that the check I wrote is wrong though

**Comment by posva** [comment]
I pushed and release a fix of something that could be related. It worked on my Nuxt project so I hope it works for you too!

**Comment by DennisSmuda** [comment]
@posva unfortunately it's worse now

Screenshot 2024-03-31 at 19 21 16

`Cannot access 'animationId' before initialization`

My Setup: 
app.vue
  - Name.vue
    - Dot.vue

Where `Dot.vue` tries to call `useSpring` and the error happens.. I could wrap the `Name` component in `ClientOnly` in `0.3.1` but this also doesn't work anymore.

**Comment by DennisSmuda** [comment]
@posva this is what I found in the debug console: 

Screenshot 2024-03-31 at 19 32 47


Let me know if I can help you 👍

**Comment by posva** [comment]
you might be using an older version, I cannot reproduce...

**Comment by DennisSmuda** [comment]
> you might be using an older version, I cannot reproduce...

I setup a fresh project and made sure `0.3.2` is installed - still the same problem:

https://github.com/DennisSmuda/vue-use-spring-ssr-bug

**Comment by posva** [comment]
Oh, I see it now, thanks. Fixed and released.

**Comment by DennisSmuda** [comment]
Works like a charm now, thank you so much @posva

**Pull request closed without merging**
